return {
  -- {
  --   "folke/which-key.nvim",
  --   event = "VeryLazy",
  --   opts = {
  --     plugins = {
  --       spelling = true,
  --       presets = {
  --         operators = false,
  --       }
  --     },
  --     defaults = {
  --       mode = { "n", "v" },
  --       ["g"] = { name = "+goto" },
  --       ["]"] = { name = "+next" },
  --       ["["] = { name = "+prev" },
  --       ["<leader><tab>"] = { name = "+tabs" },
  --       ["<leader>b"] = { name = "+buffer" },
  --       ["<leader>c"] = { name = "+code" },
  --       ["<leader>f"] = { name = "+find" },
  --       ["<leader>h"] = { name = "+hunks" },
  --       ["<leader>q"] = { name = "+quit/session" },
  --       ["<leader>s"] = { name = "+search - todos" },
  --       ["<leader>r"] = { name = "+rename" },
  --       ["<leader>u"] = { name = "+ui" },
  --       ["<leader>w"] = { name = "+workspace" },
  --       ["<leader>x"] = { name = "+diagnostics/quickfix" },
  --       ["<leader>p"] = { name = "+ai" },
  --     },
  --   },
  --   config = function(_, opts)
  --     local wk = require("which-key")
  --     wk.setup(opts)
  --     wk.register(opts.defaults)
  --   end,
  -- },
}
