vim.pack.add({ 'https://github.com/nvim-treesitter/nvim-treesitter' })

require 'nvim-treesitter.configs'.setup {
    ensure_installed = {
        'bash',
        'cmake',
        'c',
        'cpp',
        'css',
        'diff',
        'gitignore',
        'gleam',
        'go',
        'html',
        'javascript',
        'json',
        'jsonc',
        'lua',
        'markdown',
        'markdown_inline',
        'odin',
        'python',
        'query',
        'regex',
        'rust',
        'sql',
        'tsx',
        'toml',
        'typescript',
        'vimdoc',
        'vim',
        'zig',
    },
    modules = {},
    ignore_install = {},
    sync_install = false,
    auto_install = true,
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}
